name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for version bumping

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Use a specific .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Version Bumping
        id: bump-version
        uses: anothrNick/github-tag-action@1.69.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ steps.bump-version.outputs.new_tag }} -o ./packages

      - name: Publish to NuGet
        run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump-version.outputs.new_tag }}
          name: "Release ${{ steps.bump-version.outputs.new_tag }}"
          body: "Release of version ${{ steps.bump-version.outputs.new_tag }}"
          files: "./packages/*.nupkg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
